#!/bin/sh

# 在执行前 git config core.hooksPath .hooks && chmod u+x .hooks/pre-commit
FILES=$(deno fmt)
if [[ $(git diff --stat) != '' ]]; then
  echo '文件内容有改动，请先新增 fmt 后的文件'
  exit 1
else
  echo FILES
  exit 0
fi
