name: jobs
on:
  schedule:
    - cron: "0 1 * * *" # run once a day
  workflow_dispatch: {}
  push:
    branches: [main]

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Verify formatting
        run: deno fmt --check

      - name: Cache dependencies
        run: deno cache --config deno.jsonc deps.ts

      - name: Cache Chrome (Linux)
        uses: actions/cache@v2
        with:
          path: ~/.cache/deno/deno_puppeteer
          key: chrome-${{ runner.os }}-${{ hashFiles('**/import_map.json', '**/depts.ts') }}
          restore-keys: chrome-${{ runner.os }}-

      - name: Install Chromium (Unix)
        run: PUPPETEER_PRODUCT=chrome deno run -A --unstable https://deno.land/x/puppeteer@14.1.1/install.ts

      - name: Run Script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          deno run -A ./process.ts

      - name: Type check script
        run: deno check --remote process.ts
